### ISSUE TITLE
GLIBC_2.32 / GLIBC_2.34 not found when trying to run in AWS Cloud9

### ISSUE THREAD

**Issue by 094459** [sjramblings/aws-service-limits#6]
When I downloaded the binary I got the following error

```
./aws-service-limits: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./aws-service-limits)
./aws-service-limits: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./aws-service-limits)
```

AWS Cloud9 environments are using an older Amazon Linux version I believe.

```
ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Fix**

The simple fix is to just run 

```
go build
```
Which will recompile the binary that works in AWS Cloud9 environments.

(Adding this here incase anyone has a similar issue so they can google the fix)

**Comment by 094459** [comment]
Fix was to rebuild the binary using "go build"

**Comment by jonesy1234** [comment]
@094459 Thanks for raising and closing! 👍
